apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-html
data:
  index.html: |
    <html>
      <body>
        <h1>Hello from {{ .Release.Name }}</h1>
        <p>Replica count: {{ .Values.replicaCount }}</p>
      </body>
    </html>